ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CLINIC_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'RECEPTIONIST';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPPORT_STAFF';
