# ==========================================
# MedCare Generic Microservice Dockerfile
# ==========================================
FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma.config.ts ./

RUN npm install

COPY . .

RUN npm run prisma:generate:all
RUN npm run build:all

# ==========================================
# Production Runtime Image
# ==========================================
FROM node:22-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV APP_NAME=doctor-service

COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/libs/broker/proto ./libs/broker/proto

CMD ["sh", "-c", "node dist/apps/${APP_NAME}/src/main.js"]
