export const MICROSERVICES = {
  ANALYTICS: 'ANALYTICS_SERVICE',
  DOCTOR: 'DOCTOR_SERVICE',
  PATIENT: 'PATIENT_SERVICE',
  CLINIC: 'CLINIC_SERVICE',
  APPOINTMENT: 'APPOINTMENT_SERVICE',
  FINANCE: 'FINANCE_SERVICE',
  REVIEW: 'REVIEW_SERVICE',
  NOTIFICATION: 'NOTIFICATION_SERVICE',
  AUDIT: 'AUDIT_SERVICE',
  RBAC: 'RBAC_SERVICE',
  SYSTEM: 'SYSTEM_SERVICE',
  SUPPORT: 'SUPPORT_SERVICE',
  CHAT: 'CHAT_SERVICE',
} as const;

export const PATTERNS = {
  ANALYTICS: {
    GET_OVERVIEW: 'admin.analytics.overview',
  },
  DOCTOR: {
    LIST: 'admin.doctors.list',
    GET_BY_ID: 'admin.doctors.get',
    UPDATE_STATUS: 'admin.doctors.status.update',
    LIST_VERIFICATIONS: 'admin.doctors.verification.list',
    DECIDE_VERIFICATION: 'admin.doctors.verification.decision',
    PATIENT_SEARCH: 'patient.doctors.search',
    PATIENT_GET_DETAILS: 'patient.doctors.details',
    PATIENT_GET_SLOTS: 'patient.doctors.slots',
    RECEPTIONIST_SCHEDULE_GRID: 'receptionist.doctors.schedule_grid',
    RECEPTIONIST_STATUS_LIST: 'receptionist.doctors.status_list',
    DOCTOR_GET_DASHBOARD: 'doctor.dashboard.overview',
    DOCTOR_GET_WORKSPACE: 'doctor.consultation.workspace',
    DOCTOR_SAVE_NOTES: 'doctor.consultation.notes.save',
    DOCTOR_COMPLETE_CONSULTATION: 'doctor.consultation.complete',
    DOCTOR_CREATE_PRESCRIPTION: 'doctor.prescriptions.create',
    DOCTOR_LIST_PRESCRIPTIONS: 'doctor.prescriptions.list',
    DOCTOR_GET_PRESCRIPTION: 'doctor.prescriptions.get',
    DOCTOR_LIST_APPOINTMENTS: 'doctor.appointments.list',
    DOCTOR_GET_APPOINTMENT: 'doctor.appointments.get',
    DOCTOR_GET_VIDEO_TOKEN: 'doctor.appointments.video_token',
    DOCTOR_LIST_PATIENTS: 'doctor.patients.list',
    DOCTOR_GET_PATIENT_RECORDS: 'doctor.patients.records',
    DOCTOR_GET_SCHEDULE: 'doctor.schedule.get',
    DOCTOR_UPDATE_SCHEDULE: 'doctor.schedule.update',
    DOCTOR_GET_EARNINGS: 'doctor.earnings.summary',
    DOCTOR_REQUEST_PAYOUT: 'doctor.earnings.payout_request',
    DOCTOR_LIST_REVIEWS: 'doctor.reviews.list',
    DOCTOR_REPLY_REVIEW: 'doctor.reviews.reply',
    DOCTOR_GET_PROFILE: 'doctor.profile.get',
    DOCTOR_UPDATE_PROFILE: 'doctor.profile.update',
  },
  PATIENT: {
    LIST: 'admin.patients.list',
    GET_BY_ID: 'admin.patients.get',
    UPDATE_STATUS: 'admin.patients.status.update',
    GET_DASHBOARD: 'patient.dashboard.summary',
    GET_PROFILE: 'patient.profile.get',
    UPDATE_PROFILE: 'patient.profile.update',
    LIST_RECORDS: 'patient.medical_records.list',
    CREATE_RECORD: 'patient.medical_records.create',
    DELETE_RECORD: 'patient.medical_records.delete',
    LIST_PRESCRIPTIONS: 'patient.prescriptions.list',
    GET_PRESCRIPTION: 'patient.prescriptions.get',
    RECEPTIONIST_SEARCH: 'receptionist.patients.search',
  },
  CLINIC: {
    LIST: 'admin.clinics.list',
    CREATE: 'admin.clinics.create',
    UPDATE: 'admin.clinics.update',
    UPDATE_STATUS: 'admin.clinics.status.update',
    // Clinic Manager Patterns
    MANAGER_GET_BRANCH: 'clinic_manager.branch.get',
    MANAGER_UPDATE_BRANCH: 'clinic_manager.branch.update',
    MANAGER_GET_STATS: 'clinic_manager.stats.get',
    MANAGER_LIST_DOCTORS: 'clinic_manager.doctors.list',
    MANAGER_ASSIGN_DOCTOR: 'clinic_manager.doctors.assign',
    MANAGER_REMOVE_DOCTOR: 'clinic_manager.doctors.remove',
    MANAGER_LIST_STAFF: 'clinic_manager.staff.list',
    MANAGER_CREATE_STAFF: 'clinic_manager.staff.create',
    MANAGER_UPDATE_STAFF: 'clinic_manager.staff.update',
    MANAGER_DELETE_STAFF: 'clinic_manager.staff.delete',
    MANAGER_LIST_ROOMS: 'clinic_manager.rooms.list',
    MANAGER_CREATE_ROOM: 'clinic_manager.rooms.create',
    MANAGER_UPDATE_ROOM: 'clinic_manager.rooms.update',
    MANAGER_DELETE_ROOM: 'clinic_manager.rooms.delete',
    MANAGER_LIST_APPOINTMENTS: 'clinic_manager.appointments.list',
    MANAGER_LIST_QUEUE: 'clinic_manager.queue.list',
    MANAGER_FINANCIALS: 'clinic_manager.financials.summary',
    MANAGER_REPORTS: 'clinic_manager.reports.summary',
  },
  APPOINTMENT: {
    LIST: 'admin.appointments.list',
    TRANSITION_STATUS: 'admin.appointments.status.transition',
    RESCHEDULE: 'admin.appointments.reschedule',
    CANCEL: 'admin.appointments.cancel',
    PATIENT_LIST: 'patient.appointments.list',
    PATIENT_GET_BY_ID: 'patient.appointments.get',
    PATIENT_BOOK: 'patient.appointments.book',
    PATIENT_CANCEL: 'patient.appointments.cancel',
    PATIENT_RESCHEDULE: 'patient.appointments.reschedule',
    RECEPTIONIST_DASHBOARD: 'receptionist.appointments.dashboard',
    RECEPTIONIST_CHECK_IN: 'receptionist.appointments.check_in',
    RECEPTIONIST_GET_QUEUE: 'receptionist.appointments.queue_list',
    RECEPTIONIST_UPDATE_QUEUE: 'receptionist.appointments.queue_update',
    RECEPTIONIST_WALK_IN: 'receptionist.appointments.walk_in',
  },
  FINANCE: {
    LIST_TRANSACTIONS: 'admin.finance.transactions.list',
    PROCESS_REFUND: 'admin.finance.refund.process',
    GET_REPORT: 'admin.finance.reports.summary',
    PATIENT_SUMMARY: 'patient.finance.summary',
    PATIENT_INVOICES: 'patient.finance.invoices',
    PATIENT_PAY: 'patient.finance.pay',
  },
  REVIEW: {
    LIST: 'admin.reviews.list',
    MODERATE: 'admin.reviews.moderate',
    PATIENT_PENDING: 'patient.reviews.pending',
    PATIENT_SUBMIT: 'patient.reviews.submit',
    PATIENT_MY_REVIEWS: 'patient.reviews.list',
  },
  NOTIFICATION: {
    BROADCAST: 'admin.notifications.broadcast',
    LIST: 'admin.notifications.list',
    PATIENT_LIST: 'patient.notifications.list',
    PATIENT_MARK_READ: 'patient.notifications.mark_read',
    PATIENT_MARK_ALL_READ: 'patient.notifications.mark_all_read',
  },
  AUDIT: {
    LOG_EVENT: 'audit.log.created',
    LIST: 'admin.audit.list',
    RECEPTIONIST_LOGS: 'receptionist.audit.logs',
  },
  RBAC: {
    LIST_REQUESTS: 'superadmin.access_requests.list',
    DECIDE_REQUEST: 'superadmin.access_requests.decide',
    GET_MATRIX: 'superadmin.roles.matrix',
    UPDATE_PERMISSIONS: 'superadmin.roles.permissions.update',
  },
  SYSTEM: {
    HEALTH: 'superadmin.system.health',
    GET_SETTINGS: 'superadmin.settings.get',
    UPDATE_SETTINGS: 'superadmin.settings.update',
    BACKUP: 'superadmin.system.backup',
  },
  SUPPORT: {
    DASHBOARD_STATS: 'support.dashboard.stats',
    LIST_TICKETS: 'support.tickets.list',
    GET_TICKET: 'support.tickets.get',
    CREATE_TICKET: 'support.tickets.create',
    REPLY_TICKET: 'support.tickets.reply',
    ASSIGN_TICKET: 'support.tickets.assign',
    UPDATE_TICKET_STATUS: 'support.tickets.status.update',
    LIST_COMPLAINTS: 'support.complaints.list',
    GET_COMPLAINT: 'support.complaints.get',
    UPDATE_COMPLAINT_STATUS: 'support.complaints.status.update',
    ESCALATE_COMPLAINT: 'support.complaints.escalate',
    SEARCH_PATIENTS: 'support.patients.search',
    RESEND_NOTIFICATION: 'support.patients.resend_notification',
    LIST_FLAGGED_APPOINTMENTS: 'support.appointments.flagged.list',
    ASSIST_RESCHEDULE: 'support.appointments.reschedule',
    CLEAR_APPOINTMENT_FLAG: 'support.appointments.flag.clear',
    LIST_ACTIVITY_LOGS: 'support.activities.list',
  },
  CHAT: {
    LIST_CONVERSATIONS: 'chat.conversations.list',
    GET_CONVERSATION_MESSAGES: 'chat.messages.list',
    SEND_MESSAGE: 'chat.messages.send',
    MARK_AS_READ: 'chat.messages.mark_read',
    GET_UNREAD_COUNT: 'chat.unread_count.get',
    START_CONVERSATION: 'chat.conversations.start',
  },
} as const;

export const EVENTS = {
  APPOINTMENT: {
    BOOKED: 'event.appointment.booked',
    CANCELLED: 'event.appointment.cancelled',
    RESCHEDULED: 'event.appointment.rescheduled',
    CHECKED_IN: 'event.appointment.checked_in',
    COMPLETED: 'event.appointment.completed',
  },
  DOCTOR: {
    VERIFICATION_SUBMITTED: 'event.doctor.verification_submitted',
    VERIFICATION_DECIDED: 'event.doctor.verification_decided',
    PAYOUT_REQUESTED: 'event.doctor.payout_requested',
  },
  PAYMENT: {
    SUCCESS: 'event.payment.success',
    REFUNDED: 'event.payment.refunded',
  },
  NOTIFICATION: {
    DISPATCH: 'event.notification.dispatch',
  },
  AUDIT: {
    RECORD: 'event.audit.record',
  },
  QUEUE: {
    STATE_CHANGED: 'event.queue.state_changed',
  },
} as const;
